<!DOCTYPE html>
<html lang="vi">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>404 - Trang không tồn tại</title>
  <link rel="stylesheet" href="/utils/styles/styles.css" />
  <link rel="stylesheet" href="/utils/styles/globals.css" />
  <style>
    @keyframes spin-slow {
      from {
        transform: rotate(0deg);
      }

      to {
        transform: rotate(360deg);
      }
    }

    .animate-spin-slow {
      animation: spin-slow 3s linear infinite;
    }
  </style>
</head>

<body>
  <div class="min-h-screen bg-gradient-to-br from-white via-sky-50 to-sky-100 py-10 relative overflow-hidden">

    <!-- Animated Background Elements -->
    <div class="absolute inset-0">
      <!-- Geometric Grid Pattern -->
      <div class="absolute inset-0 opacity-20">
        <div class="grid grid-cols-8 md:grid-cols-12 lg:grid-cols-16 grid-rows-8 md:grid-rows-12 lg:grid-rows-16 h-full w-full">
          <!-- Grid items will be generated by JavaScript -->
        </div>
      </div>

      <!-- Floating Particles -->
      <div class="absolute inset-0 pointer-events-none">
        <!-- Particles will be generated by JavaScript -->
      </div>

      <!-- Diagonal Lines -->
      <div class="absolute inset-0 opacity-10">
        <!-- Diagonal lines will be generated by JavaScript -->
      </div>
    </div>

    <!-- Main Content -->
    <div class="relative z-10 min-h-screen flex items-center justify-center px-4 sm:px-6 lg:px-8">
      <div class="text-center max-w-4xl mx-auto">

        <!-- Animated Icons -->
        <div class="flex justify-center items-center space-x-4 md:space-x-8 mb-8 md:mb-12">
          <div class="transform transition-all duration-500">
            <div class="w-12 h-12 md:w-16 md:h-16 bg-sky-500 rounded-full flex items-center justify-center animate-spin-slow">
              <!-- Target icon component -->
            </div>
          </div>
          <div class="transform transition-all duration-700">
            <div class="w-16 h-16 md:w-20 md:h-20 bg-white border-4 border-sky-400 rounded-full flex items-center justify-center shadow-lg">
              <svg xmlns="http://www.w3.org/2000/svg" class="lucide lucide-swords-icon lucide-swords text-regular-blue-cl" width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <polyline points="14.5 17.5 3 6 3 3 6 3 17.5 14.5" />
                <line x1="13" x2="19" y1="19" y2="13" />
                <line x1="16" x2="20" y1="16" y2="20" />
                <line x1="19" x2="21" y1="21" y2="19" />
                <polyline points="14.5 6.5 18 3 21 3 21 6 17.5 9.5" />
                <line x1="5" x2="9" y1="14" y2="18" />
                <line x1="7" x2="4" y1="17" y2="20" />
                <line x1="3" x2="5" y1="19" y2="21" />
              </svg>
            </div>
          </div>
          <div class="transition-all duration-500">
            <div class="flex items-center justify-center animate-bounce">
              <!-- Shield icon component -->
              <div class="block h-[110px] w-[150px] overflow-hidden relative">
                <img src="/images/UI/ghost.webp" alt="Logo" class="absolute top-[-22px] left-0 h-[150px] min-w-[150px]">
              </div>
            </div>
          </div>
        </div>

        <!-- 404 Text with Glitch Effect -->
        <div class="relative mb-6 md:mb-8">
          <h1 class="text-8xl md:text-9xl lg:text-[12rem] font-black text-sky-500 leading-none select-none">
            404
          </h1>
          <h1 class="absolute inset-0 text-8xl md:text-9xl lg:text-[12rem] font-black text-sky-300 leading-none select-none transform translate-x-1 translate-y-1 opacity-70">
            404
          </h1>
          <h1 class="absolute inset-0 text-8xl md:text-9xl lg:text-[12rem] font-black text-sky-700 leading-none select-none transform -translate-x-1 -translate-y-1 opacity-70">
            404
          </h1>
        </div>

        <!-- Error Message -->
        <div class="space-y-4 md:space-y-6 mb-8 md:mb-12">
          <h2 class="text-2xl md:text-4xl lg:text-5xl font-bold text-gray-800 leading-tight">
            TRANG KHÔNG TỒN TẠI
          </h2>
          <p class="text-lg md:text-xl text-gray-600 max-w-2xl mx-auto leading-relaxed px-4">
            Có vẻ như bạn đã đi lạc trong thế giới Valorant. Trang bạn tìm kiếm không tồn tại hoặc đã được di chuyển.
          </p>
        </div>

        <!-- Action Buttons -->
        <div class="flex flex-col sm:flex-row gap-4 md:gap-6 justify-center items-center max-w-lg mx-auto">
          <button
            onclick="window.location.href='/'"
            class="group w-full sm:w-auto inline-flex items-center justify-center px-6 md:px-8 py-3 md:py-4 bg-regular-blue-cl hover:bg-sky-600 text-white font-bold rounded-xl transition-all duration-300 transform hover:scale-105 hover:shadow-xl shadow-sky-500/25">
            <!-- Home icon component -->
            <span class="text-base md:text-lg">Về trang chủ</span>
            <!-- ArrowLeft icon component -->
          </button>

          <button
            onclick="window.history.back()"
            class="group w-full sm:w-auto inline-flex items-center justify-center px-6 md:px-8 py-3 md:py-4 bg-white hover:bg-gray-50 text-sky-500 font-bold rounded-xl border-2 border-solid border-sky-500 hover:border-sky-600 transition-all duration-300 transform hover:scale-105 hover:shadow-xl">
            <!-- RefreshCw icon component -->
            <span class="text-base md:text-lg">Quay lại</span>
          </button>
        </div>
      </div>
    </div>

    <!-- Bottom Decoration -->
    <div class="absolute bottom-0 left-0 right-0 h-1 bg-gradient-to-r from-sky-400 via-sky-500 to-sky-400 animate-pulse"></div>

    <div id="ghost-logo" hidden class="absolute bottom-8 right-[-100px] rotate-[-30deg] h-[300px] w-[300px] overflow-hidden">
      <img src="/images/UI/ghost.webp" alt="Logo" class="absolute top-[-90px] left-[-90px] h-[500px] min-w-[500px]">
    </div>
  </div>

  <script defer>
    // Generate floating particles
    const particlesContainer = document.querySelector('.absolute.inset-0.pointer-events-none');
    for (let i = 0; i < 15; i++) {
      const particle = document.createElement('div');
      particle.className = 'absolute w-1 h-1 md:w-2 md:h-2 bg-sky-400 rounded-full animate-bounce opacity-60';
      particle.style.left = `${Math.random() * 100}%`;
      particle.style.top = `${Math.random() * 100}%`;
      particle.style.animationDelay = `${i * 0.3}s`;
      particle.style.animationDuration = `${2 + Math.random() * 2}s`;
      particlesContainer.appendChild(particle);
    }

    function randomOneToFour() {
      const arr = [1, 2, 3, 4];
      return arr[Math.floor(Math.random() * arr.length)];
    }

    const randomGhostPosition = () => {
      const randomPosition = randomOneToFour();
      const ghost = document.getElementById('ghost-logo');
      if (randomPosition !== 4) {
        ghost.classList.remove('bottom-8', 'right-[-100px]', 'rotate-[-30deg]');
      }
      if (randomPosition === 1) {
        ghost.classList.add('bottom-8', 'left-[-100px]', 'rotate-[30deg]');
      } else if (randomPosition === 2) {
        ghost.classList.add('top-8', 'right-[-100px]', 'rotate-[-120deg]');
      } else if (randomPosition === 3) {
        ghost.classList.add('top-8', 'left-[-100px]', 'rotate-[120deg]');
      }
      ghost.hidden = false
    }

    randomGhostPosition();
  </script>
</body>

</html>